-- schema.sql
-- Baut die Spesen-Datenbank in einem LEEREN Supabase-Projekt auf.
-- Abgeleitet aus dem echten Stand des Live-Projekts vom 09.10.2026
-- (supabase/stand-abfragen.sql). Gedacht für das Testprojekt.
--
-- Im SQL Editor des NEUEN Projekts einmal komplett ausführen.
-- NICHT im Live-Projekt ausführen — dort steht das alles schon.
--
-- Nicht übernommen: die Altlast-Tabelle spesen_admin.

-- ============================================================
-- Tabellen
-- ============================================================

create table public.spesen_benutzer (
  email    text primary key,
  name     text,
  rolle    text not null default 'user' check (rolle in ('admin', 'user')),
  aktiv    boolean not null default true,
  erstellt timestamptz not null default now()
);

create table public.spesen_konto (
  id            bigint generated by default as identity primary key,
  nummer        text not null unique,
  bezeichnung   text not null,
  mwst          numeric(4,2) not null default 8.1,
  sortierung    integer not null default 100,
  aktiv         boolean not null default true,
  auftrag_modus text not null default 'alle',
  auftrag_liste text[]
);

create table public.spesen_beleg (
  id           bigint generated by default as identity primary key,
  geraet       text not null,
  beleg_datum  date not null,
  betrag       numeric(10,2) not null check (betrag > 0),
  mwst         numeric(4,2) not null,
  konto_nummer text not null,
  auftrag_nr   text not null,
  positionen   jsonb,
  zahlart      text not null default 'karte'
               constraint spesen_beleg_zahlart_pruefung
               check (zahlart in ('karte', 'bar', 'vorkasse')),
  bemerkung    text,
  datei_pfad   text,
  monat        text not null,
  status       text not null default 'offen',
  erstellt     timestamptz not null default now(),
  geaendert    timestamptz not null default now()
);
create index spesen_beleg_geraet_monat_idx on public.spesen_beleg (geraet, monat);

create table public.spesen_favorit (
  id           bigint generated by default as identity primary key,
  geraet       text not null,
  name         text not null,
  konto_nummer text not null,
  auftrag_nr   text not null,
  auftrag_name text,
  sortierung   integer not null default 100,
  erstellt     timestamptz not null default now()
);
create index spesen_favorit_geraet_idx on public.spesen_favorit (geraet);

create table public.spesen_periode (
  id         bigint generated by default as identity primary key,
  geraet     text not null,
  name       text not null,
  von        date not null,
  bis        date not null,
  sortierung integer not null default 0,
  erstellt   timestamptz not null default now()
);

-- ============================================================
-- Funktionen und Trigger
-- ============================================================

create or replace function public.ist_admin()
 returns boolean
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select exists (
    select 1 from spesen_benutzer
    where email = auth.jwt() ->> 'email' and rolle = 'admin' and aktiv
  );
$function$;

create or replace function public.periode_grenze()
 returns trigger
 language plpgsql
as $function$
begin
  if (select count(*) from spesen_periode where geraet = new.geraet) >= 3 then
    raise exception 'Höchstens drei Perioden je Benutzer. Bitte zuerst eine löschen.';
  end if;
  return new;
end;
$function$;

create trigger periode_grenze_trigger
  before insert on public.spesen_periode
  for each row execute function public.periode_grenze();

-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.spesen_benutzer enable row level security;
alter table public.spesen_konto    enable row level security;
alter table public.spesen_beleg    enable row level security;
alter table public.spesen_favorit  enable row level security;
alter table public.spesen_periode  enable row level security;

-- Benutzer: lesen nur sich selbst, Admin alle. Schreiben nur die Edge Function.
create policy benutzer_lesen on public.spesen_benutzer
  for select to authenticated
  using ((email = (auth.jwt() ->> 'email')) or ist_admin());

-- Konten: alle lesen, nur Admin anlegen und ändern. Löschen gibt es nicht.
create policy konto_lesen on public.spesen_konto
  for select to authenticated using (true);
create policy konto_admin_neu on public.spesen_konto
  for insert to authenticated with check (ist_admin());
create policy konto_admin_aendern on public.spesen_konto
  for update to authenticated using (ist_admin()) with check (ist_admin());

-- Belege
create policy beleg_lesen on public.spesen_beleg
  for select to authenticated
  using ((geraet = (auth.jwt() ->> 'email')) or ist_admin());
create policy beleg_anlegen on public.spesen_beleg
  for insert to authenticated
  with check ((geraet = (auth.jwt() ->> 'email')) and (status = 'offen'));
create policy beleg_aendern on public.spesen_beleg
  for update to authenticated
  using      (((geraet = (auth.jwt() ->> 'email')) or ist_admin()) and (status = 'offen'))
  with check (((geraet = (auth.jwt() ->> 'email')) or ist_admin()) and (status = 'offen'));
create policy beleg_loeschen on public.spesen_beleg
  for delete to authenticated
  using ((geraet = (auth.jwt() ->> 'email')) and (status = 'offen'));

-- Favoriten: nur die eigenen
create policy favorit_eigene on public.spesen_favorit
  for all to authenticated
  using      (geraet = (auth.jwt() ->> 'email'))
  with check (geraet = (auth.jwt() ->> 'email'));

-- Perioden: nur die eigenen
create policy periode_eigene_lesen on public.spesen_periode
  for select to authenticated using (geraet = (auth.jwt() ->> 'email'));
create policy periode_eigene_neu on public.spesen_periode
  for insert to authenticated with check (geraet = (auth.jwt() ->> 'email'));
create policy periode_eigene_aendern on public.spesen_periode
  for update to authenticated
  using (geraet = (auth.jwt() ->> 'email')) with check (geraet = (auth.jwt() ->> 'email'));
create policy periode_eigene_weg on public.spesen_periode
  for delete to authenticated using (geraet = (auth.jwt() ->> 'email'));

-- ============================================================
-- Rechte
-- Ohne grant kommt trotz Policy alles leer zurück. Neuere Supabase-Projekte
-- vergeben diese Rechte nicht mehr von selbst — darum ausdrücklich.
-- ============================================================

grant usage on schema public to authenticated;
grant select, insert, update, delete on
  public.spesen_benutzer, public.spesen_konto, public.spesen_beleg,
  public.spesen_favorit, public.spesen_periode
  to authenticated;
grant execute on function public.ist_admin() to authenticated;

-- ============================================================
-- Storage: Bucket "belege", privat, 10 MB, Bilder und PDF
-- Jeder legt in seinem Ordner ab (E-Mail mit _ statt @ und .),
-- Admins lesen alles.
-- ============================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('belege', 'belege', false, 10485760,
        array['image/jpeg','image/png','image/heic','image/heif','image/webp','application/pdf']);

create policy beleg_datei_ablegen on storage.objects
  for insert to authenticated
  with check ((bucket_id = 'belege') and ((storage.foldername(name))[1] =
    replace(replace((auth.jwt() ->> 'email'), '@', '_'), '.', '_')));

create policy beleg_datei_lesen on storage.objects
  for select to authenticated
  using ((bucket_id = 'belege') and (((storage.foldername(name))[1] =
    replace(replace((auth.jwt() ->> 'email'), '@', '_'), '.', '_')) or ist_admin()));

create policy beleg_datei_loeschen on storage.objects
  for delete to authenticated
  using ((bucket_id = 'belege') and ((storage.foldername(name))[1] =
    replace(replace((auth.jwt() ->> 'email'), '@', '_'), '.', '_')));
